### ISSUE TITLE
Experiment with different sands and ball sizes

### ISSUE THREAD

**Issue by ratnaweera** [ratnaweera/sandtrails#11]

**Comment by ratnaweera** [comment]
Baking soda looks way more promising than sand.

**Comment by monitorlizard** [comment]
Haha, incidentially I have 6 bags of expired baking soda sitting on my desk

**Comment by ratnaweera** [comment]
13mm steel balls seem to be a good fit for the size of the table. 20mm was a bit large.

Approx. 80g of baking soda will cover the area of the plate quite well (tray with diameter of roughly 400mm). First dropped 150g on there, but that seemed too much. Scooped out some. Will weigh once to be sure.
