### ISSUE TITLE
Implement shutdown properly

### ISSUE THREAD

**Issue by monitorlizard** [ratnaweera/sandtrails#12]
Currently not available graphically, only throught /shutdown
Is the webserver expected to shut down as well?

**Comment by ratnaweera** [comment]
Sorry for the long pause!
I believe the "shutdown" feature is only needed/useful during the development phase. It calls GIP.cleanup() which is useful when you try to re-start the program without powering off the raspi in between.
So no, I don't think we need the webserver to shutdown right now. Typing in /shutdown in the URL for now is fine. (for me at least)

**Comment by ratnaweera** [comment]
I need to correct myself: When running "headerless" (no screen attached), it would be useful to have a safe way to power down the raspi remotely. Can we call something like "sudo shutdown -h now" from within the webserver if we wanted to?

**Comment by ratnaweera** [comment]
Done in 157816ec2c2f00276e99c2ced32191f9397e3ac4 
Should be "spiced" up graphically a bit, but I'll close this issue for now
