### ISSUE TITLE
Integration of LED hardware

### ISSUE THREAD

**Issue by ratnaweera** [ratnaweera/sandtrails#6]
Play around with existing LED strip. How to control, how to wire up, how many segments do we want?

**Comment by monitorlizard** [comment]
The existing LED strip DF1-300-950-HCP is **white** only. 
24V Brightness can be adjusted using PWM.
Datasheet: https://www.led1.de/shop/files/Datenblaetter/Bars-Strips/SOLAROX_Diffuse_LED_Streifen.pdf

**Comment by ratnaweera** [comment]
Crap, sorry!  We played around with so many different LED lights that I forgot which one this one is.
Could you look for something that makes more sense? We have some neopixel LED matrices, but no other LED strips...

**Comment by monitorlizard** [comment]
I'll probably buy these: 
https://tutorials-raspberrypi.de/raspberry-pi-ws2801-rgb-led-streifen-anschliessen-steuern/

**Comment by ratnaweera** [comment]
Excellent! Looks good 👍🏽
